apiVersion: v1
kind: Pod
metadata:
  name: mongo-client
  namespace: default
spec:
  containers:
  - name: mongo
    image: mongo:latest
    command: ['sleep']
    args: ['3600']
  restartPolicy: Never

