apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-facing-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-facing-webserver
  template:
    metadata:
      labels:
        app: customer-facing-webserver
    spec:
      containers:
      - name: customer-facing-webserver
        image: {{ .Values.webServer.image }}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-facing-webserver
spec:
  selector:
    app: customer-facing-webserver
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000  # Choose any available port number
  type: NodePort

