apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
  - name: kafka-client
    image: wurstmeister/kafka:latest
    command: ["sleep"]
    args: ["3600"]
  restartPolicy: Never

